### ISSUE TITLE
When I try to print a custom report using base_report_to_printer it throws an error (odoo Enterprise v10)

### ISSUE THREAD

**Issue by libukoshy** [OCA/report-print-send#100]
When I try to print a custom report using base_report_to_printer it throws an error like 

TypeError: unbound method search() must be called with ir.actions.report.xml instance as first argument (got Cursor instance instead)

Below is the error log ------------

Odoo Server Error
Traceback (most recent call last):
  File "/home/libu/Odoo/odoo-10/Addons-10/web/controllers/main.py", line 70, in wrap
    return f(*args, **kwargs)
  File "/home/libu/Odoo/odoo-10/Addons-10/web/controllers/main.py", line 1477, in index
    request.session.db, request.session.uid, request.session.password, report_id])
  File "/home/libu/Odoo/odoo-10/odoo/http.py", line 118, in dispatch_rpc
    result = dispatch(method, params)
  File "/home/libu/Odoo/odoo-10/odoo/service/report.py", line 35, in dispatch
    res = fn(db, uid, *params)
  File "/home/libu/Odoo/odoo-10/addons-extra/base_report_to_printer/report_service.py", line 41, in exp_report_get
    [('report_name', '=', report_name)])
TypeError: unbound method search() must be called with ir.actions.report.xml instance as first argument (got Cursor instance instead)

![git_sc1](https://user-images.githubusercontent.com/4153342/28573115-269906c8-7167-11e7-8717-3ab550487336.png)
![git_sc1](https://user-images.githubusercontent.com/4153342/28573131-30fc5f8e-7167-11e7-8768-85db98019a32.png)
![git_sc2](https://user-images.githubusercontent.com/4153342/28573139-3b27be9a-7167-11e7-9e8f-d09609eed791.png)

**Comment by nbornand** [comment]
Encountering the same issue. 
It seems the "report" argument of Printer.print_document was changed from the whole report to a string with the report's name. But now some print_options() have been adapted to the string signature while the same method in printer_tray still expect the full report. Which of the two is the right way? Cheers
