### ISSUE TITLE
Architecture dependent?

### ISSUE THREAD

**Issue by luca-vercelli** [OCA/report-print-send#113]
(talking about base_report_to_printer module) If I am not wrong, this module relies on CUPS, so it will work only in Linux and not in Windows servers. Is this correct? If so, you should really write that in module description, just to avoid time wastings for end users.

**Comment by luca-vercelli** [comment]
Just for record, for people running Windows, I have created a modified version of base_report_to_printer that works in Windows:
https://www.odoo.com/apps/modules/10.0/base_report_to_printer_win/

**Comment by lasley** [comment]
Yeah `base_report_to_printer` is CUPS dependent.

How deep were the changes you needed to make? Is this something we could make an interface/adapter system for so that we can have both modules live in harmony?

**Comment by lasley** [comment]
Also, you mean interfacing with Windows servers and not running on a Windows server right? Because this module should work on Windows AFAIK, it just can't print into a Windows based print server

**Comment by luca-vercelli** [comment]
> you mean interfacing with Windows servers

Yes, I want to use as a print server the same Windows server where Odoo is installed.
Currently you need another *nix server to use as print server.
Also, I don't mean to use *another* Windows server as print server, because that is *really*  difficult to do IMHO.

> How deep were the changes

Well, I tried to keep the basic structure untouched.

However, I have removed the "printing_server" and "printing_job" models because I did not need them. You only have 1 (local) server, and no control on printing jobs. Anyway, we could imagine to keep two kinds of servers, "CUPS servers" and one "Windows local server".

In order to print in Windows, you need to install some external tools, please see the "Installation" and "Configuration" sections in the link above. Maybe we can imagine to have two distinct behaviours, one for "CUPS servers" and one for "Windows local server".

**Comment by luca-vercelli** [comment]
@lasley I can work on a pull request to merge the two modules. I just wait to know if you* like the approach I have just described: a single Windows print server, no jobs for that server, ghostscript and gsview used for print.

you = I mean you and all interested developers

**Comment by lasley** [comment]
@luca-vercelli - Your approach is solid I think, and could also be adapted into Linux support (no CUPS).

Give me a week or so, I plan on making us a base interface mechanism so that we can more easily use the code in unison. Basically we would treat the print server types as a "driver" of sorts, with the option to enable or disable the job aspect of things.

> ghostscript and gsview used for print.

Where does the ghostscript come in?

**Comment by luca-vercelli** [comment]
print_file() calls gsprint.exe.
gsprint.exe is part of GSView. It also requires ghostscript.exe to convert PDF->PS.
When I say  GSView I mean http://pages.cs.wisc.edu/~ghost/gsview/get50.htm and not http://www.gsview.com/.

You can see the code at https://github.com/luca-vercelli/odoo-modules/blob/de5293e5fd1faf5e971e6d888a522d9687fc9672/base_report_to_printer_win/models/printing_printer.py#L103

The full command (gsprint+ghostscript) is stored in ir.config_parameter: 
https://github.com/luca-vercelli/odoo-modules/blob/de5293e5fd1faf5e971e6d888a522d9687fc9672/base_report_to_printer_win/views/ghostscript.xml#L6
