### ISSUE TITLE
[11.0] Unable to generate a report without being member of Print/User group

### ISSUE THREAD

**Issue by Garamotte** [OCA/report-print-send#134]
When a user wants to generate a report, the `_get_user_default_print_behaviour` method searches for the default printer. This operation needs at least Printer/User access rights, so we have to give this group to all employees.
In addition, this error is silenced, and the traceback is not available server-side, it's only displayed in the browser's debug console.

I think that we should check the access rights before searching for a printer.

**Comment by pedrobaeza** [comment]
Or maybe with `sudo`? Which version?

**Comment by Garamotte** [comment]
I had the issue on version 11.0, don't know for other versions.

**Comment by pedrobaeza** [comment]
Well, you know better than me the module, so you can take the best technical decision 😉

**Comment by schout-it** [comment]
Only thing I did not test yet, is automatic sale confirmation of website sales and portal users.
do not now it they also need access to these objects or if there should be a different flow in those cases
(would expect that for portal users, you almost always send to client)
