### ISSUE TITLE
Issue Connecting to Print Server

### ISSUE THREAD

**Issue by atmerhaut** [OCA/report-print-send#137]
Running V10 Enterprise on Rosehosting. Need to connect to a LAN server with Ubuntu that has our printers installed. When setting up our Rosehosting Odoo instance, for the server do we use the public IP or our internal IP for the Ubuntu machine with port 631? When using the Public IP we immediately get an error saying it cannot connect to our server and make sure CUPS is running (which it is). Using the local IP just loads for awhile, then we are disconnected then reconnected again and nothing changes.

**Comment by pedrobaeza** [comment]
Sorry, but it's a problem with your network. Check firewalls and configurations.

**Comment by vysakhbt** [comment]
@atmerhaut I also have the same issue. Have you resolved this. ?Please help me if you have.
Thanks in advance
