### ISSUE TITLE
Field name 'default' (printing.printer) is reserved in postgresql !

### ISSUE THREAD

**Issue by alexis-via** [OCA/report-print-send#142]
As I was banging my head trying to understand why "select * from printing_printer" WORKS, but:

```
o0_test2=# select id, default from printing_printer;
ERROR:  syntax error at or near "default"
LINE 1: select id, default from printing_printer;
```

I discovered that 'default' is a reserved word in postgres:
https://www.postgresql.org/docs/current/static/sql-keywords-appendix.html
So we should not use it as field name.

Field definition in source code: https://github.com/OCA/report-print-send/blob/11.0/base_report_to_printer/models/printing_printer.py#L42
Moreover, I think it's a pretty bad idea to have a boolean field "default", with code to make sure that only one entry has the "true" value. There are several ways to handle this in a better way...

**Comment by yelizariev** [comment]
You can send a pr to odoo with a constrain to field name

**Comment by yelizariev** [comment]
But for master branch
