### ISSUE TITLE
Update to V10.0.2.01 Copies Error

### ISSUE THREAD

**Issue by atmerhaut** [OCA/report-print-send#145]
Have base_report_to_printer installed on Odoo V10 Enterprise. When trying to update the module to v10.0.2.01 I am getting the following message.

> Odoo Server Error
> Traceback (most recent call last):
>   File "/opt/odoo10/odoo10-server/odoo/http.py", line 641, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/opt/odoo10/odoo10-server/odoo/http.py", line 683, in dispatch
>     result = self._call_function(**self.params)
>   File "/opt/odoo10/odoo10-server/odoo/http.py", line 333, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/opt/odoo10/odoo10-server/odoo/service/model.py", line 101, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/opt/odoo10/odoo10-server/odoo/http.py", line 326, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/opt/odoo10/odoo10-server/odoo/http.py", line 941, in __call__
>     return self.method(*args, **kw)
>   File "/opt/odoo10/odoo10-server/odoo/http.py", line 506, in response_wrap
>     response = f(*args, **kw)
>   File "/opt/odoo10/odoo10-server/addons/web/controllers/main.py", line 894, in call_button
>     action = self._call_kw(model, method, args, {})
>   File "/opt/odoo10/odoo10-server/addons/web/controllers/main.py", line 882, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/opt/odoo10/odoo10-server/odoo/api.py", line 689, in call_kw
>     return call_kw_multi(method, model, args, kwargs)
>   File "/opt/odoo10/odoo10-server/odoo/api.py", line 680, in call_kw_multi
>     result = method(recs, *args, **kwargs)
>   File "/opt/odoo10/odoo10-server/odoo/addons/base/module/module.py", line 528, in button_immediate_upgrade
>     return self._button_immediate_function(type(self).button_upgrade)
>   File "/opt/odoo10/odoo10-server/odoo/addons/base/module/module.py", line 485, in _button_immediate_function
>     modules.registry.Registry.new(self._cr.dbname, update_module=True)
>   File "/opt/odoo10/odoo10-server/odoo/modules/registry.py", line 83, in new
>     odoo.modules.load_modules(registry._db, force_demo, status, update_module)
>   File "/opt/odoo10/odoo10-server/odoo/modules/loading.py", line 335, in load_modules
>     force, status, report, loaded_modules, update_module)
>   File "/opt/odoo10/odoo10-server/odoo/modules/loading.py", line 237, in load_marked_modules
>     loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
>   File "/opt/odoo10/odoo10-server/odoo/modules/loading.py", line 156, in load_module_graph
>     _load_data(cr, module_name, idref, mode, kind='data')
>   File "/opt/odoo10/odoo10-server/odoo/modules/loading.py", line 95, in _load_data
>     tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
>   File "/opt/odoo10/odoo10-server/odoo/tools/convert.py", line 845, in convert_file
>     convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
>   File "/opt/odoo10/odoo10-server/odoo/tools/convert.py", line 915, in convert_xml_import
>     obj.parse(doc.getroot(), mode=mode)
>   File "/opt/odoo10/odoo10-server/odoo/tools/convert.py", line 799, in parse
>     self._tags[rec.tag](rec, de, mode=mode)
>   File "/opt/odoo10/odoo10-server/odoo/tools/convert.py", line 707, in _tag_record
>     id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
>   File "/opt/odoo10/odoo10-server/odoo/addons/base/ir/ir_model.py", line 1190, in _update
>     record.write(values)
>   File "/opt/odoo10/odoo10-server/odoo/addons/base/ir/ir_ui_view.py", line 380, in write
>     return super(View, self).write(self._compute_defaults(vals))
>   File "/opt/odoo10/odoo10-server/odoo/models.py", line 3578, in write
>     field.determine_inverse(records)
>   File "/opt/odoo10/odoo10-server/odoo/fields.py", line 1045, in determine_inverse
>     getattr(records, self.inverse)()
>   File "/opt/odoo10/odoo10-server/odoo/addons/base/ir/ir_ui_view.py", line 220, in _inverse_arch
>     view.write(data)
>   File "/opt/odoo10/odoo10-server/odoo/addons/base/ir/ir_ui_view.py", line 380, in write
>     return super(View, self).write(self._compute_defaults(vals))
>   File "/opt/odoo10/odoo10-server/odoo/models.py", line 3560, in write
>     self._write(old_vals)
>   File "/opt/odoo10/odoo10-server/odoo/models.py", line 3724, in _write
>     self._validate_fields(vals)
>   File "/opt/odoo10/odoo10-server/odoo/models.py", line 1081, in _validate_fields
>     raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
> ParseError: "Error while validating constraint
> 
> Field `report_copies` does not exist
> 
> Error context:
> View `ir.actions.report.xml.printing`
> [view_id: 2054, xml_id: base_report_to_printer.act_report_xml_view, model: ir.actions.report.xml, parent_id: 7]
> None" while parsing /opt/odoo10/custom/addons/base_report_to_printer/views/ir_actions_report_xml_view.xml:4, near
> <record model="ir.ui.view" id="act_report_xml_view">
>     <field name="name">ir.actions.report.xml.printing</field>
>     <field name="model">ir.actions.report.xml</field>
>     <field name="inherit_id" ref="base.act_report_xml_view"/>
>     <field name="arch" type="xml">
>       <xpath expr="//page[@name='security']" position="before">
>         <page string="Print" name="print">
>           <group>
>             <field name="property_printing_action_id"/>
>             <field name="report_copies"/>
>             <field name="printing_printer_id"/>
>           </group>
>           <separator string="Specific actions per user"/>
>           <field name="printing_action_ids"/>
>         </page>
>       </xpath>
>     </field>
>   </record>

**Comment by pedrobaeza** [comment]
You have to update the module, not only to refresh code and restart.

**Comment by atmerhaut** [comment]
I downloaded the new module, replaced the one on our server, then in Odoo clicked upgrade. When I click upgrade is when I am getting the error message.

**Comment by pedrobaeza** [comment]
Try to uninstall old version and install new one.

**Comment by atmerhaut** [comment]
I uninstalled in Odoo, removed the folder, then put the new folder on, updated apps list, and installed. Still getting the same error.

**Comment by pedrobaeza** [comment]
Well, the module is working perfectly on our runbot, so it's not a problem of the module itself. Maybe you have other modules that interfere.

**Comment by atmerhaut** [comment]
It says that the field "report_copies" does not exist. Where should it be getting that from? Is it needed, or can I just comment out that line in the code?

**Comment by atmerhaut** [comment]
Once I commented out that line in /view/ir_actions_report_xml_view.xml the module installed fine. After setting all of our preferences back on reports and user accounts, it appears to be working.
