### ISSUE TITLE
ZPL2 parameters - quantity 

### ISSUE THREAD

**Issue by PhilippeBach** [OCA/report-print-send#149]
I need to print product labels  how to put the products filds like name in the label fields 
what is the right syntax to add those fields in the label ?

is it possble to add quantity of labels to print ?

**Comment by pedrobaeza** [comment]
Sorry, this is not an issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or OCA mailing lists (https://odoo-community.org/groups), but not here.

Closing this by the reason above.
