### ISSUE TITLE
Unable to install dependencies on odoo.sh env

### ISSUE THREAD

**Issue by odooadvantage** [OCA/report-print-send#151]
Please can you tell me the process of how to install the dependencies required for this module on odoo.sh. I put the dependencies in requirements.txt file but in the log I can see clear that no package found.
**Logs:**
File "/usr/local/lib/python2.7/dist-packages/pip/_internal/index.py", line 533, in find_requirement
'No matching distribution found for %s' % req
DistributionNotFound: No matching distribution found for cups==2.1.3-4

**Comment by pedrobaeza** [comment]
Why are you fixing the cups version?

**Comment by odooadvantage** [comment]
What I do to install it cleanly? If I don't put it in the requirement.txt file then I get error like this.
No module found 
Unable to import cups

**Comment by pedrobaeza** [comment]
Yes, but put only `cups`, not `cups==2.1.3-4`

**Comment by sbidoul** [comment]
`cups` does not exist as a python distribution on pypi. Use [pycups](https://pypi.org/project/pycups/) in your requirements file.

That said, I'm not sure odoo.sh is going to have the necessary systems dependencies (such as cups itself).

**Comment by odooadvantage** [comment]
But in the python file `cups` is imported and in the readme file it is clearly said to install `cups`. I tried `pycups` too but getting same error.
What do if odoo.sh don't have the necessary dependencies? Can you report this issue to odoo? Or can you tell me any alternative?

**Comment by sbidoul** [comment]
Note the documentation says `apt-get install cups` for the system dependency, and `pip install pycups` for the python library. Usually only pip installable python libraries can go in requirements.txt, not system dependencies. I believe odoo.sh does a simple pip install with the content of requirements.txt.

odoo.sh is not managed by the OCA, you should contact odoo for further support.

**Comment by pedrobaeza** [comment]
Yeah, indeed, closing this.
