### ISSUE TITLE
Unable to install module "base_report_to_printer" because an external dependency is not met: No module named cups

### ISSUE THREAD

**Issue by schawale** [OCA/report-print-send#155]
Unable to install module "base_report_to_printer" because an external dependency is not met: No module named cups 

After install all dependency
Odoo .Ver:11
Os: Ubuntu 16.04
Cups ver: 2.1.3-4ubuntu0.4

**Comment by etobella** [comment]
You need to install pycups following the readme explanation...

**Comment by schawale** [comment]
root@ubuntu:~# sudo apt-get install cups
Reading package lists... Done
Building dependency tree
Reading state information... Done
cups is already the newest version (2.1.3-4ubuntu0.4).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
root@ubuntu:~# sudo -H pip install pycups
Requirement already satisfied: pycups in /usr/local/lib/python2.7/dist-packages                  (1.9.73)
root@ubuntu:~# sudo apt-get install python3-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-dev is already the newest version (3.5.1-3).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
root@ubuntu:~# sudo apt-get install libcups2-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libcups2-dev is already the newest version (2.1.3-4ubuntu0.4).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
root@ubuntu:~# sudo apt-get install cups
Reading package lists... Done
Building dependency tree
Reading state information... Done
cups is already the newest version (2.1.3-4ubuntu0.4).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

**Comment by etobella** [comment]
Try with `pip3 install pycups`. You installed it on Python 2.7

**Comment by schawale** [comment]
thanks. done
much change in installation manual 
![image](https://user-images.githubusercontent.com/8260698/42029463-4c8fd31c-7aed-11e8-8949-fb364b849fb5.png)
