### ISSUE TITLE
base_report_to_printer opens a copy of sent report

### ISSUE THREAD

**Issue by yvaucher** [OCA/report-print-send#16]
An improvement would be to avoid opening the report.

Previously we did an attempt to raise a warning message to give a feed back to the user that the report has been printed. But this was breaking the workflow when printing multiple reports. So it needs some improvements.

**Comment by sebalix** [comment]
I just checked the code. Maybe adding a new `printing.action` named `server_no_client`, and making the `exp_report_get()` method quiet with it would solve the problem?

**Comment by ferdiga** [comment]
(1)
def _available_action_types(self):
    return [('server', 'Send to Printer'),
            ('client', 'Send to Client'),
            ('user_default', "Use user's defaults"),
            ]
should include 
- "both" - "sent to printer" should not open the report on the screen as it happens now
- "mail_to" - we used this to send long running reports to the user or even external emails, once finished. 
  external emails could be considered as a security risk.
  it's an easy way to forward reports
- "save as" - especially if a working dav solution is available. this needs a better file naming mechanism using the selection criteria as part of the name.

(2)
for many reports it will not be possible to define the action_type on report level, but on print dialog level - Examples:
- trial balance
- general ledger - typically
  *\* all accounts per year -> printer only
  *\* to look up and print or not period moves of an account -> screen only

the running time - and hence the target - of the report depends on the selection criteria.

it would be great if all report dialogs would be able to grab the report target selection once the module is installed.
