### ISSUE TITLE
Issues with installation and pycups

### ISSUE THREAD

**Issue by seven18it** [OCA/report-print-send#161]
Hi we are not able to install the module without the pycups dependency. And we faced many errors installing pycups on windows. Is there any other way to install pycups ?

Errors we issued in installing pycups are attached as an image. Please help. Thanks 

![capture](https://user-images.githubusercontent.com/34323922/45864321-ff540d80-bdbc-11e8-81ed-32b0c0954938.JPG)

**Comment by etobella** [comment]
In order to install pycups, you need to install cups on your computer, but it is only available for linux 
https://www.cups.org/
This module is not available for windows.
