### ISSUE TITLE
base_report_to_printer, ubuntu 18.04 and crashes

### ISSUE THREAD

**Issue by alexis-via** [OCA/report-print-send#163]
On Odoo v10, since I upgraded from Ubuntu 16.04 to Ubuntu 18.04, I get some crashes when calling print_document().

```
Traceback (most recent call last):
  File "/home/odoo/erp/odoo/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/erp/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/erp/odoo/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/erp/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/erp/odoo/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/erp/odoo/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/erp/odoo/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/erp/odoo/addons/web/controllers/main.py", line 899, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/erp/odoo/addons/web/controllers/main.py", line 887, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/erp/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/erp/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/erp/barroux-prod/barroux_vpc/stock.py", line 95, in print_delivery_label
    printer.print_document(zpl_fname, zpl_file, 'raw')
  File "/home/odoo/erp/report-print-send/base_report_to_printer/models/printing_printer.py", line 111, in print_document
    file_name, report=report, copies=copies, format=format)
  File "/home/odoo/erp/report-print-send/base_report_to_printer/models/printing_printer.py", line 129, in print_file
    options=options)
IPPError: (1280, u'Aucun fichier ou dossier de ce type')
```

The printer works well when I do:
```
lp -h 192.168.10.106 -d zebra /home/odoo/test1.zpl
request id is zebra-66877 (1 file(s))
```

But, when I run:
```
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cups
>>> conn = cups.Connection(host='192.168.10.106')
>>> conn.printFile('zebra', '/home/odoo/test1.zpl', 'test', {'raw': 'True'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cups.IPPError: (1280, u'No such file or directory')
>>> conn.printFiles('zebra', ['/home/odoo/test1.zpl'], 'test', {'raw': 'True'})
0
```

So I made a patch on base_report_to_printer that calls "printFiles" instead of "printFile" with the second argument as a list.
I really don't know why there is this problem ! It seems like a bug in the python cups lib.
I open this bug report for those that may be hit by this problem.

**Comment by alexis-via** [comment]
Here is my patch https://people.via.ecp.fr/~alexis/base_report_to_printer-1804.diff

Too early and too strange to make a PR so far...

**Comment by alexis-via** [comment]
I get this problem with pycups==1.9.74 and when I used the Ubuntu package python-cups provided by ubuntu 18.04 (1.9.73-2).

**Comment by alexis-via** [comment]
My patch proposed in my second comment didn't work ; it avoided the crash, but it wouldn't print anything (I was debugging remotely, so I couldn't see that it was not printing).

After a very very long debugging session, I finally found a strange solution: to avoid the problem, I need to create a file /etc/cups/client.conf that contains "ServerName 192.168.10.102". The IP address must be the IP address of a CUPS server, but it may be a different address than the one given to cups.Connection(host=xxx) ; the IP used as CUPS server will be the one given via cups.Connection().

I think that it's a bug in libcups2 provided by Ubuntu 18.04.

**Comment by alesisjoan** [comment]
I had the same issue. However it only fail in a specific printer, 2 other printers were ok. The 3 printers are hardly the same model.

I tried with your PR and did the same: no error but no print.

Finally, i installed cups in another server and worked.

libcups version not working: 2.2.7-1ubuntu2.6
**libcups version working ok: 2.2.7-1ubuntu2.7**

**Comment by doudz** [comment]
On Ubuntu 18.04
I have the same issue using both 2.2.7-1ubuntu2.7 and 2.2.7-1ubuntu2.6
and both pycups 1.9.73 or 1.9.74

but works good using 2.2.10-4ubuntu2.1 (on Ubuntu 19.04)

**Comment by renzo1974** [comment]
As there is currently not fix I have created a workaround by using lp command when printFile will fail.

Here is my patch. Maybe it is also helpful for others...
The patch is available here. https://gist.github.com/rm-jamotion/0453e91ff3e13350a1e46a11ebb02e8d
