### ISSUE TITLE
Keep on generating PDF

### ISSUE THREAD

**Issue by stesifrancesco** [OCA/report-print-send#167]
Hi....I am trying to use this module, I have installed and configured everything.
I create a report with this configurations:
Default Behaviour | Send to Printer
-- | --
Default Printer | Samsung M267x 287x Series
Paper Source | Printer Default

but when I try to use it only generate a PDF.

I'm using Odoo 11 on Ubuntu 17 and 18
No error raised

Thanks in advance for yours help

Francesco

**Comment by fhrancis** [comment]
Hi
Same issue on Odoo 10 and Ubuntu 16.
Added my user to the group "Printing / Print User"
Configured the Default Printer and set "Printing action" = Send to Printer
When I press Print button under Sale Order it generates the PDF without sending it directly to the printer.
