### ISSUE TITLE
How can we connect the printer with server

### ISSUE THREAD

**Issue by vvipi91** [OCA/report-print-send#170]
Hi, 

 I just installed the base_report_to_printer in a server and configured odoo in that server. How can i connect the printer there. Do i need to configure my printer in server? While i checked the module locally it works as well. But with the server , How can i configure the printer there?

**Comment by pedrobaeza** [comment]
You need a CUPS server and put the IP there.

**Comment by vvipi91** [comment]
Do we have any example for connecting printer to cups server and adding it in server. beacuse printers are on my local server and my odoo installation is on server.

**Comment by pedrobaeza** [comment]
This is not something about Odoo, but sysadmin work. You have to open a connection to your local CUPS server for being accessible to Odoo server.

**Comment by vvipi91** [comment]
Do we have any example for connecting printer to cups server and adding it in server. beacuse printers are on my local server and my odoo installation is on server.

**Comment by vysakhbt** [comment]
@vvipi91 I have the same issue.Have you rectified it ?

**Comment by pedrobaeza** [comment]
@vysakhbt please stop spamming all issues.

**Comment by vysakhbt** [comment]
Sorry for the trouble @pedrobaeza
