### ISSUE TITLE
You try to install module 'remote_report_to_printer' that depends on module 'base_remote'. But the latter module is not available in your system.

### ISSUE THREAD

**Issue by younismahsud** [OCA/report-print-send#175]
I am getting an error message when try to install `remote_report_to_printer` but I could not find any such module. Following is the error message. I am using odoo v11 enterprise edition.

> You try to install module 'remote_report_to_printer' that depends on module 'base_remote'.
But the latter module is not available in your system.

**Comment by pedrobaeza** [comment]
Just have `base_remote` available in your addons path: https://github.com/OCA/server-tools/tree/11.0/base_remote

**Comment by younismahsud** [comment]
Thank you @pedrobaeza . I got it.

**Comment by wintzarchihtun** [comment]
Hello, I got same error like this when installing project_sla third party.Following is the error message. I am using odoo v12 community edition. 

You try to install module 'project_sla' that depends on module 'project_issue'.
But the latter module is not available in your system.

**Comment by younismahsud** [comment]
@wintzarchihtun please download 'project_issue' module from this link and place it in your directory.
Link: https://www.odoo.com/apps/modules/11.0/project-issue/
