### ISSUE TITLE
Update Printers from CUPS crash 502

### ISSUE THREAD

**Issue by a87b01c14** [OCA/report-print-send#178]
When running a multi-worker thread, the thread exits abnormally when calling cups.Connection(), in the process_zombie() method, wpid, status = os.waitpid(-1, os.WNOHANG)
The status value is 11

`DEBUG odoo odoo.api: call printing.printer.update.wizard(12,).action_ok() 

 DEBUG odoo odoo.service.server: Worker (92849) unregistered `

**Comment by flotho** [comment]
Hi @a87b01c14 
did you succeed in making this work ?
