### ISSUE TITLE
[12.0] base_report_to_printer: Do no print e-mail attachment

### ISSUE THREAD

**Issue by rven** [OCA/report-print-send#183]
The problem I encountered when using this module was the following:

A report was defined to be send to a printer.
So when printing the document this functionality works fine.

But when the report is attached to a e-mail template, the document was also printed on the defined printer. This action should not be triggered at all.

The solution is the following:

```python
from odoo import models


class MailTemplate(models.Model):
    _inherit = "mail.template"

    def generate_email(self, res_ids, fields=None):
        return super(MailTemplate, self.with_context(
            must_skip_send_to_printer=True
        )).generate_email(res_ids, fields=fields)
```

The problem here is that the module does not depend on mail... 

Any suggestions are welcome.

**Comment by rven** [comment]
@pedrobaeza can you have a look at the issue?

**Comment by pedrobaeza** [comment]
You should do a glue module `base_report_to_printer_mail` depending on both that adds this part, and make it auto-installable.

**Comment by rven** [comment]
https://github.com/OCA/report-print-send/pull/185
