### ISSUE TITLE
[11] AttributeError: 'PdfFileWriter' object has no attribute 'appendPagesFromReader'

### ISSUE THREAD

**Issue by rafagf1** [OCA/report-print-send#184]
When printing documents and generating the pdf file, the PyPDF2 version 1.18 shows the error with 'appendPagesFromReader' and this attribute is used by 'odoo/addons/base/ir/ir_actions_report.py'

Currently the PyPDF2 version is 1.26, is there any reason to force the version to 1.18 (https://github.com/OCA/report-print-send/commit/6280913bd2241b771edde9e45e18eae7b32291ed)?

Thanks in advance

**Comment by pedrobaeza** [comment]
It was the one put previously on Travis: https://github.com/OCA/report-print-send/commit/93d3727a17fc42c6386bc100962a1a7d0d7b8f67#diff-354f30a63fb0907d4ad57269548329e3L45
