### ISSUE TITLE
Allow to print multiple QWeb reports in a single batch

### ISSUE THREAD

**Issue by bodedra** [OCA/report-print-send#187]
Hello Team,

We are planning to release our one module on OCA, which will allow us print multiple QWeb reports in a single batch.

For example, picking, packing, reports needs to be printed together in a single batch.

So would you please suggest us to best/related OCA repository name to submit it ?

**Comment by bodedra** [comment]
@guewen votes for OCA/reporting-engine

**Comment by pedrobaeza** [comment]
Yeah, I think OCA/reporting-engine is the best host for this. Maybe this can be achieved already with https://github.com/OCA/web/tree/12.0/web_ir_actions_act_multi

**Comment by bodedra** [comment]
@pedrobaeza Thank you. I will try with your suggested module and compare output. Will update you shortly.

**Comment by bodedra** [comment]
@pedrobaeza I have installed this module and it doesn't provide a facility to configure batch report from UI. It seems we have develop logic according suggested code block in readme.rst file to get desire batch report.

**Comment by pedrobaeza** [comment]
Yeah, but maybe can serve as base for your module.

**Comment by bodedra** [comment]
We have already developed module without your recommendation base module. :smile: So let's see how it goes. I will close this issue here and submit module at OCA/reporting-engine repository. Appreciate your help.
