### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by guidev224** [OCA/report-print-send#197]
Working on odoo 11 CE I am trying to install base_report_to_printer on  a linux server 16.04 LTS I have followed all steps indicated in the readme file but when I try to import cups I get the following error:
```
>>> import cups
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/cups/__init__.py", line 19
    return f"ES{ree_id}{dist_id}{control_letter}{control_2_letter}"
                                                                  ^
SyntaxError: invalid syntax
```

**Comment by bodedra** [comment]
It seems this is issue of cups library installation in your environment. You may reinstall it or remove existing version and install it fresh.

**Comment by guidev224** [comment]
@bodedra 
But the install tells me that the installation was successful, so I don't get the issue's origin
