### ISSUE TITLE
error: Unable to install module "base_report_to_printer" because an external dependency is not met: No module named cups

### ISSUE THREAD

**Issue by ahmedlatif** [OCA/report-print-send#198]
module: base_report_to_printer
version: 12.0

I have followed the steps to install cups and the module
When I try installing the module in Odoo I get the error 
"Unable to install module "base_report_to_printer" because an external dependency is not met: No module named cups"

**Comment by pedrobaeza** [comment]
You don't have the external dependency correctly put, but this is out of scope of this issue tracker. There's no problem with the module.
