### ISSUE TITLE
print also to remote printer? 

### ISSUE THREAD

**Issue by codeagencybe** [OCA/report-print-send#199]
Hello,

Apologizes if my question is wrongly formulated, I'm trying to understand how this report-print-send module works and if this fits a requirement for an upcoming project. 
And it's my first time in the territory of this kind of field. 
We have done some Zebra printing before but with iotbox which is very easy. 

We are running Odoo on a cloud server, no printers are installed or connected directly to the server. 
But my customer wants to pass the print job for EU A4 paper size prints (packing slip, invoices, etc...) directly from Odoo to printer without the hassle to download PDF > file > print > set properties > print.
Just 1 click print and done.

As I understand this module can do exactly this or offer the functionality to make it possible. 
But does this only work if the printer is installed on the server directly or also from a local network at the customer side where Odoo web interface can "see" the printers from the network? 
Does this also require the server to install drivers/dependencies like CUPS? 

Thanks for the feedback!

**Comment by wpichler** [comment]
We also have the same requirement here - i do think about putting a small raspberry based box on client side - acting as print server - connected using some sort of vpn with the remote odoo server.

**Comment by AlexisTonneau** [comment]
Any update on this issue ?

**Comment by wpichler** [comment]
I think this is no real issue  - and can get closed. We are now using a raspberry as print server at the customer location, which does connect using vpn to the same network where also the odoo server is connected. Does work like a charm....

**Comment by wpichler** [comment]
We have this already done now - but we had to patch the print_file function a little bit to use a os.command to lp to print. PyCups always return 1030 error when we tried to print remote. Using the lp command did worked just fine.
So it would be a great thing, if the printer model would be able to have an option (print using pycups, print using lp). And if using lp - then just use this code:

```
        _logger.info(
            'Sending job to CUPS printer %s on %s'
            % (self.system_name, self.server_id.address))
        options = self.print_options(report=report, **print_opts)
        options_str = ""
        for option, value in options.items():
            options_str += "-o %s=%s" % (option, value, )
        _logger.info("Cmd: %s", 'lp -h %s:%s -d %s %s %s' %
                  (self.server_id.address,
                   self.server_id.port,
                   self.system_name,
                   options_str,
                   file_name))
        os.system('lp -h %s:%s -d %s %s %s' %
                  (self.server_id.address,
                   self.server_id.port,
                   self.system_name,
                   options_str,
                   file_name))
        _logger.info("Printing job: '%s' on %s" % (
            file_name,
            self.server_id.address,
        ))
```

**Comment by wpichler** [comment]
@AlexisTonneau What do you think about this ?

**Comment by AntonioChagoya** [comment]
hello! 

I'm planning to do something very similar to what you did @wpichler 
I was hoping to avoid using a raspberry, because we have many POS and installing/maintaining each one, would be a pain.

My plan was creating a python script and running it as a service on each machine

I'm not very familiar with manipulating hardware from a cloud instance so I'm working under a few suppositions.

I'll elaborate so we can discuss a better approach, and anyone with the same issue can follow a clear path in the future.

1. In order for the cloud instance to send printing instructions to a local machine, the local machine should expose an IP to the internet (we can discuss how safe this is, and how to protect the local machine)
2. Server on the local machine exposes the port, handle the printing request and send it to printers
3. Since local server has access to computer resources, it can simply use a controller to access and send data to printers
4. Cloud instance, would have to send the "ticket" or object being print, as a blob or other format so server can process it
5. Raspberry would follow a very similar approach but without compromising the local computer 

Almost sure I'm missing details, and also not sure if avoiding raspberry is a good idea, any comments are appreciated

**Comment by codeagencybe** [comment]
Point 1 for security can be managed with a VPN tunnel like wireguard+head scale or if you prefer a managed service something like tailscale, netbird, etc ...

Basically all devices will run in the same extended network via VPN protocol. And services can also see each other and you can give each device a dedicated IP or VPN domain. 

This is how we solve the problem with remote printers with 1 (virtual) IOT box on enterprise as well. Let's say you have 2 physical warehouses on different address, with VPN you can use 1 IOT box and it can even see printers from the other address and send print jobs. Just keep on mind there can be a small lag/delay like this but acceptable. Doesn't has to be an IOT to be clear. You can connect any kind of device through that VPN network. 

We also use it to protect SSH access to servers. Without VPN the machine reports ssh port not available unless you first connect into the same VPN network. 

Hopefully that gives you some info on how that handle that security problem.

**Comment by AntonioChagoya** [comment]
Okay, so let me see if I understand

There is one central server, which acts as a virtual IoT Box, running on a VPN, I assume then you have two servers, one that holds Odoo and the one that holds the "virtual IoT box", on the other hand each POS computer, can access the shared network using the VPN to make it secure

What is the purpose of a physical box if this can be done?

**Comment by codeagencybe** [comment]
You don't need another server. Your odoo server is just your cloud server. It can also run wireguard and headscale if you want to self host that. Otherwise you opt for a commercial managed VPN like tailscale. They have a free plan up to 5 devices or something like that. 

Your client/POS systems also remain and they run the virtual IOT or if you don't want IOT you do something like a direct print based on IP. Since your VPN will give you a unique IP from "inside" the VPN network it will be reachable from anywhere in the world by another device that is also in the same VPN network. It basically looks like as if everyone is in the local network but in reality it's not. 

It's best if you check and try out tailscale first to make it easy to understand the concept first. Once that concept clicks, it's easy to deviate to self hosted open source alternatives like wireguard and headscale

**Comment by AntonioChagoya** [comment]
thanks @codeagencybe! I'll get back with the results, but this is very useful information
