### ISSUE TITLE
No module named cups error on install despite all external dependencies being met

### ISSUE THREAD

**Issue by augustosamame** [OCA/report-print-send#216]
Odoo v10
Ubuntu 14.04
cups installed via apt-get install cups

cups is already the newest version (2.1.3-4ubuntu0.11).

both requirements satisfied:

Requirement already satisfied: cups in /home/ubuntu/.local/lib/python2.7/site-packages (from -r requirements.txt (line 43)) (0.0.6)
Requirement already satisfied: pycups in /home/ubuntu/.local/lib/python2.7/site-packages (from -r requirements.txt (line 44)) (1.9.73)

I even installed python3 version of pycups:

Requirement already satisfied (use --upgrade to upgrade): pycups in /usr/local/lib/python3.5/dist-packages

restarted server

However I still get an error on installing the module for a missing external dependancy: No module named cups

I don't know what else to try. Thanks in advance for your help.

**Comment by pedrobaeza** [comment]
Sorry, but this is a deployment problem, not a problem of the module. The `cups` library is not installed on the Python environment where Odoo is being run. Check venvs or Docker or whatever you have used for deployment Odoo.

**Comment by augustosamame** [comment]
Helo @pedrobaeza I understand why you may think this is a deployment issue but:

1) not using venv / docker as this is an Odoo production server. just Odoo running on plain Ubuntu.
2) I HAVE installed cups library both with pip (and pip3 just in case), and also added it to requirements.txt and installed from there.

I always get:

`Requirement already satisfied: cups in /home/ubuntu/.local/lib/python2.7/site-packages (0.0.6)`

Despite that, the module does not recognize the cups library as being installed.

**Comment by pedrobaeza** [comment]
You can see on the try me on runbot button of the module that this is working, so it's not a problem of the module itself. Access the same python environment you are using for running Odoo and try to mimic the import order (`import cups`) that is doing the module. Anyway, the Python library is `pycups`, not `cups`.

**Comment by augustosamame** [comment]
I will do as you say. Thank you.
Bear in mind that as indicated in my original comment, *pycups* library is
ALSO installed, so at least the error message is wrong, as it asks about
cups, not pycups. Anyway, I'll try to solve it on my end and report back.
