### ISSUE TITLE
Not sending to CUPS

### ISSUE THREAD

**Issue by terencefaul** [OCA/report-print-send#219]
module: base_report_to_printer
version: 12.0

**Steps to reproduce**
- I send a report to the printer and behaviour is the same as normal PDF printing.

Do below modules need to be installed on the machine running Odoo, or the machine running the CUPS server?.
Does the CUPS server need to be on the same machine as the Odoo instance?

 sudo apt-get install libcups2-dev
sudo apt-get install python3-dev

I have a Odoo instance running on a VM, and the CUPs running on another VM.
Odoo can access and update the printers, even the jobs can be seen in Odoo.

When I send the report to the printer I simply still get the PDF dialog.
No errors are present in the logs

**Comment by yvaucher** [comment]
https://github.com/OCA/report-print-send/tree/12.0/base_report_to_printer#installation

```
To install this module, you need to:

  *  Install PyCups - https://pypi.python.org/pypi/pycups

sudo apt-get install cups
sudo apt-get install libcups2-dev
sudo apt-get install python3-dev
sudo pip install pycups
```

This is on your Odoo server.

I cannot assist with VM though.

**Comment by terencefaul** [comment]
Yannick

Thank you for your reply. I have done that and still I just get the PDF Dialoge

Regards

Regards

Terence Faul
