### ISSUE TITLE
Directly sending Text to a ZPL printer opens a download window. 

### ISSUE THREAD

**Issue by Protoneer** [OCA/report-print-send#241]
I am trying to print ODOO reports to a ZPL compatible label printer. 

The reports are QWEB generated and report_type is TEXT.

The code below only deals with PDF direct Printing and opens a download window of the text generate report.

Is there a way that I can make it send the text to the printer instead of opening a download window?

JS  that only deals with PDF's
https://github.com/OCA/report-print-send/blob/0e0b3f290ea7d4ca944c23278a063ee7aba03b2e/base_report_to_printer/static/src/js/qweb_action_manager.js#L12-K46

Model code:
https://github.com/OCA/report-print-send/blob/0e0b3f290ea7d4ca944c23278a063ee7aba03b2e/base_report_to_printer/models/ir_actions_report.py#L102-L118

**Comment by Protoneer** [comment]
I have considered the Printer_ZPL2 addon but I have more control over my labels with QWEB and the labels I am bringing in have already been designed and the ZPL layout is ready to be used for me.

**Comment by saxomanu** [comment]
Hi,
I have the same issue. I'm trying to override to deal with type text.
I have a bug, but when it's work, i plan to do a PR

**Comment by etobella** [comment]
Well, the standard usage is to configure it with printer_zpl2 that is already flexible and allows a lot of configuration. At least is what I have done and works perfectly

**Comment by FrancoCumplidoS** [comment]
> Bueno, el uso estándar es configurarlo con printer_zpl2 que ya es flexible y permite mucha configuración. Al menos es lo que he hecho y funciona perfectamente

Could you explain to me how the module works? the truth tried to make it work a thousand times without success
