### ISSUE TITLE
[ZPL II LOGIC IMPLEMENTATION]

### ISSUE THREAD

**Issue by FrancoCumplidoS** [OCA/report-print-send#250]
Greetings,
I'm trying to implement ZPL II in the Odoo Inventory module but I don't know how to implement it ... the idea is that an option to print "X" ZPL appears in the delivery order printing menu. 

I don't understand how the .py and .xml files in the wizard folder work and are related!! 

Help me Please!!!

**Comment by pedrobaeza** [comment]
Sorry, this is not an issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
