### ISSUE TITLE
"Update Printer" button cause odoo.sh odoo-server to restart. 

### ISSUE THREAD

**Issue by odoo-sh** [OCA/report-print-send#291]
Odoo Version: V14.0
Python Version: 3.8.10 
Environment: Odoo.sh 

What are the steps to reproduce your issue?
- Install https://github.com/OCA/report-print-send in odoo.sh
- Configure the CUPS server with printer policy
AuthType Default
Require user @SYSTEM
Order deny,allow
- Expose the CUPS port to external world
- Configure the Printer server in Odoo with CUPS server External IP and Port. Add the system username, password, optionally select encryption method.
- Perform the "Update Printer" button operation.

What is the current behavior that you observe?
- The server connection disconnects and reconnects, leaving the dialogue box to remain opened. Observed that Odoo.sh Process get restart every time the "Update Printer" button is pressed. It works without CUPS Authentication.

What would be your expected behavior in this case?
- When the report-to-print > "Update Printer" button is pressed, Odoo-server should not restart.

**Comment by fbndsprz** [comment]
Same problem. No log or error. Odoo server just restarts after successful completion of action_update_printers()
