### ISSUE TITLE
odoo freezes after send document to print

### ISSUE THREAD

**Issue by NadozirnySvyatoslav** [OCA/report-print-send#358]
## Module
base_report_to_printer 

## Describe the bug
Stock picking function write overrided with:
```
from odoo import models

class Picking(models.Model):
    _inherit = "stock.picking"

    def write(self, vals):
        res = super(Picking, self).write(vals)
        if self.sale_id and (vals.get('state', False) == 'done' or vals.get('date_done', False)):
            if len(self) == 1:
                receipt = self.env.ref('my_module.action_saleorder_invoice_print')
                if receipt:
                    receipt.print_document( [self.sale_id.id] )
        return res
```
Mostly it works fine when cups response, but sometimes  it freezes odoo at all and I have to kill and restart server

## To Reproduce
17.0e 

1. Add model stock.picking with overrided function write
2. Done picking
3. Odoo freezes

**Expected behavior**
Maybe some exception or writing to the log error. Maybe should be started in separated thread 

**Additional context**
odoo 17.0e
python 3.10.12
ubuntu 22.04 LTS
cups  2.4.1op1-1ubuntu4.8

**Comment by ioans73** [comment]
@NadozirnySvyatoslav Have you been able to solve it? I have the same problem.

**Comment by NadozirnySvyatoslav** [comment]
Yes, I made workaround solution, so in my case it works with some minor fixes, but I hope does not need to commit pull request

**Comment by ioans73** [comment]
Thanks for your response.
FYI, I solved it by increasing the number of workers, without modifying any code.

**Comment by NadozirnySvyatoslav** [comment]
In my case it works temporarily  - after appears again, so I move printing to another function to be executed from qweb, not from backend
