### ISSUE TITLE
Pingen module should be a print provider

### ISSUE THREAD

**Issue by philhug** [OCA/report-print-send#41]
https://github.com/odoo/odoo/pull/3050

**Comment by guewen** [comment]
The `print` addon for print providers is an Enterprise addon, I don't think we want this community addon to depend on an Enterprise addon.

**Comment by mart-e** [comment]
@philhug please see slide 16 of [Odoo licensing presentation](https://www.odoo.com/slides/slide/open-source-licenses-196) about depending on a proprietary module

**Comment by philhug** [comment]
@mart-e well, I assumed that the print addon should have been merged to master. At least the original PR suggested that.
If the print addon is really meant to be enterprise-only, then yes, we can't depend on it.

**Comment by mart-e** [comment]
@philhug that PR was from October 2014, before the enterprise repository existed.
