### ISSUE TITLE
Print queue functionality

### ISSUE THREAD

**Issue by StefanRijnhart** [OCA/report-print-send#45]
Hi,

we are playing with base_print_report_send to allow asynchronous printing, opening a new thread for each print. Occasionally this leads to an exhaustion of available database connections. One solution could be to implement a proper print queue using the connector framework. Has anyone done any work on asynchronous printing in this direction or otherwise?

Thanks,
Stefan

**Comment by guewen** [comment]
Hi,

We've not worked on that but it is for sure interesting.

**Comment by dreispt** [comment]
A slightly different approach, but it would be nice to have a "job processing queue" and the ability to send jobs to the queue. The basic use case is to request report generating to a file format (pdf, xls, csv,...).

**Comment by StefanRijnhart** [comment]
Good one. That would be the right level of granularity.

**Comment by sbidoul** [comment]
@StefanRijnhart do you plan to integrate with connector? To generate the report? And/or to actually send it to cups (which has a queuing mechanism too)?

**Comment by clonedagain** [comment]
Having a print queue is what CUPS is for. What need do we have to duplicate this in Odoo ? If you spool very big jobs continuously you just need to match the connection pool's size to your usage don't you?
I've probably missed something but it would help if you could please explain a bit more.

**Comment by StefanRijnhart** [comment]
OK, actual use case: big warehouse with lots of MTO orders. Customized the 8.0 picking interface so that a product barcode is printed in the background (using threading.Thread), as well as the outgoing picking if it is the first incoming product picked for this picking. For each product barcode, the outgoing picking is looked up and its order number is printed on the barcode so these are printed individually. Printing needs to be asynchronous because each print takes up between 400 and 800 miliseconds. If I open a thread for each picked product and someone increments a picked product quantity with 150, I create a fork bomb with 150 threads and 150 database connections. Increasing the database connections to say 500 or 1000 is no guarantee that this number of connections is outrun. I could group prints by order number and keep fingers crossed we will never hit that limit but having a print queue (or a more generalized job queue as Daniel suggests) on the Odoo side seems like a very elegant solution for this problem, minimizing resources that would otherwise be wasted most of the time on keeping this large number of database connections available.

**Comment by sbidoul** [comment]
@StefanRijnhart why not use connector instead of creating threads? It _is_ a generalized job queue. And with the jobrunner, as soon as a job is posted it starts immediately, provided there is available capacity. Moreover the jobrunner channels is a mechanism to precisely control the number of parallel jobs.

**Comment by StefanRijnhart** [comment]
@sbidoul That was my exact proposal ;-)

**Comment by clonedagain** [comment]
OK so the problem you have is that you have a lot of very small reports and you can't spool them as one big job. Then I see why you'd need the connector indeed.

In this light, we may actually have the same need for invoices and other commercial materiel : we may want to batch-process them on a digital press (or print subcontractor) instead of printing one document at a time.

**Comment by clonedagain** [comment]
@lbellier you may be interested.

**Comment by gdgellatly** [comment]
@StefanRijnhart do you still have this requirement.  I never knew, I had implemented very roughly years ago not even using base_report_to_printer but plain old lpr with a cron job, a print queue model with simple retries and a workflow hook.  Anyhow, I am in the process of porting all that work to use OCA/queue and base_report_to_printer.  #102 

~~Unfortunately I need help on porting base_report_to_printer to v11 first as the javascript is not my forte and thats all changed with removal of report model.~~ (Not anymore)

**Comment by StefanRijnhart** [comment]
Sorry, I was only on this particular project for a short time and I don't think we implemented it eventually. However, I have gained a lot of experience with the queue job mechanism and I would totally go this way if I had to do it today.
