### ISSUE TITLE
[8.0] Document prints to printer AND to client

### ISSUE THREAD

**Issue by SVQTQ** [OCA/report-print-send#48]
Hello

So I am on odoo8, using the base_report_to_printer module and this sends the pdf to the client as well.

I am on win10, using chrome. Win7, using chrome also has this issue.

Workflow:
I set the user's default_action to send to printer with the correct printer chosen.
I do the same for the report.
I log in as the user of which I just set the default action
Open an invoice, print using the action

expected behaviour:
The document prints from my printer.

actual behaviour:
The document prints from my printer, but also presents me the download screen.

![user](https://cloud.githubusercontent.com/assets/3642183/12088290/1d8f607e-b2da-11e5-8bd6-760fc7e6e7c5.PNG)
![user_setting](https://cloud.githubusercontent.com/assets/3642183/12088291/1da0fd3e-b2da-11e5-8744-a9a369773567.PNG)
![action](https://cloud.githubusercontent.com/assets/3642183/12088293/1dacc2b8-b2da-11e5-86c1-f98782de13fd.PNG)
![report_settings](https://cloud.githubusercontent.com/assets/3642183/12089305/ba6d8962-b2e3-11e5-8f1b-4b50a558e977.PNG)

**Comment by guewen** [comment]
Are you using the last version of the addon? This has been fixed in #23. 

Do you see the notification as shown in #23?

**Comment by guewen** [comment]
> Are you using the last version of the addon? This has been fixed in #23.
> 
> Do you see the notification as shown in #23?

Reading it again, I think it has been fixed for new QWeb reports but not for the RML ones. I am not sure there is an easy way to correct that for the RML reports.

**Comment by SVQTQ** [comment]
Hi Guewen

I tried this for a qweb-template (the account_invoice one) and had the same issue.
The document gets sent to the printer, but it also opens my file explorer to ask me where I want to download the file.

**Comment by RoelAdriaans** [comment]
I've seen the same with the module web_pdf_preview module installed, just now. 
Uninstalling that module solved the problem, at least for me.

**Comment by pedrobaeza** [comment]
Is that an OCA module? Are you talking of `attachment_preview` module?

**Comment by RoelAdriaans** [comment]
No, it is not an oca module: https://github.com/buke/odoo-web-pdf-preview-print

**Comment by pedrobaeza** [comment]
I recommend you then to switch to the OCA one, and maybe put an issue record in the other repo.

**Comment by pedrobaeza** [comment]
Closing this one as answered.
