### ISSUE TITLE
RunBot - Install cups and pycups

### ISSUE THREAD

**Issue by lasley** [OCA/report-print-send#54]
Please install `cups` and `libcups2-dev` apts + `pylint` python package on RunBot in order to support merge of #52 when ready

https://runbot.odoo-community.org/runbot/build/3150169

```
UserError: (u'Unable to install module "base_report_to_printer" because an external dependency is not met: No module named cups', None)
```

**Comment by dreispt** [comment]
Runbot should use MQT to install the modules.

**Comment by pedrobaeza** [comment]
@gurneyalex I can't install binaries in runbot. Can you check?

@dreispt, this kind of tasks can't be performed automatically

**Comment by lasley** [comment]
I remember there being a discussion a while back about using Travis2Docker on the OCA RunBot, but I can't for the life of me find it. @moylop260 I'm pretty sure you were involved in this convo too, do you remember the outcome by chance?

Using that module solved literally all of my dependency issues for the long term, but there is definitely some overhead - mainly in terms of drive space. I am not the person that has to manage all of this (or that pays for the servers) so definitely not my call, but maybe worth another discussion?

**Comment by moylop260** [comment]
> @lasley ...but I can't for the life of me find it...

https://github.com/OCA/maintainer-quality-tools/issues/313#issuecomment-183051671

**Comment by moylop260** [comment]
...and @alan196 share us the following video https://youtu.be/Ul3bUMyzCPE

**Comment by gurneyalex** [comment]
done

**Comment by moylop260** [comment]
@gurneyalex 
Now you are back... 👋  we could discuss the use of runbot for long term.
In order to reduce the quantity of issues related with installation of packages (pip, apt).

We have a proposal with runbot dockerized but I don't know if is a good idea for you.

**Comment by gurneyalex** [comment]
@moylop260 this is _not_ the place to discuss the runbot. Please take the discussion to the contributors mailing list.

**Comment by moylop260** [comment]
@gurneyalex 
Thanks for reply.
Thread created: https://odoo-community.org/groups/contributors-15/contributors-43677?mode=thread&date_begin=&date_end=
