### ISSUE TITLE
base_report_to_printer 8.0.0.2.0 Calling the report programmatically executes both send to client and send to printer

### ISSUE THREAD

**Issue by cooshy** [OCA/report-print-send#55]
Calling the report from button action executes both send to client and send to printer at the same time.

Here is the piece of code I wrote to call the report:

```
    @api.multi
    def button_action(self):
        data = self.read([self.id])[0]

        datas = {
            'ids'       : [],
            'model'     : 'xz.transaction',
            'form'      : data,
            'context'   : self.env.context
        }
        return {
            'type': 'ir.actions.report.xml',
            'report_name': 'xz_retail_store.xz_transaction_printout_template',
            'datas': datas,
        }
```

**Comment by cooshy** [comment]
Hi, is there any reason why my post isn't getting any response? If so please tell me and I'll update the detail.

**Comment by pedrobaeza** [comment]
If nobody answers is because nobody has the issue or know the answer. Remember that this is something volunteer. If you have a solution, please make the PR.

**Comment by lasley** [comment]
#56 looks related too

**Comment by Garamotte** [comment]
Hi,
Did you try to add `must_skip_send_to_printer` in the context ?
This should prevent the `get_pdf` method of the report to send the document to the printer.

**Comment by pedrobaeza** [comment]
No answer from the author, so I close.
