### ISSUE TITLE
print an invoice each time you send it by mail

### ISSUE THREAD

**Issue by PhilippeBach** [OCA/report-print-send#56]
I use to print my invoices when they are created but i use the email to customer fonctionality to send the invoice by mail to my customer and odoo send a pdf to the printer each time i create a mail, ever when i change the email template 
it use a lot of paper 

on Odoo V8

**Comment by lasley** [comment]
Hi @PhilippeBach - thanks for the report. 

To confirm - when you send an invoice using the `Send by Email` button, this is both sending an email to the customer and printing via the external interface?

Does this happen on all users?

**Comment by PhilippeBach** [comment]
yes, on all users we use to print invoices directly to printer for all users

i think it is because the invoice created in email dont have the same name, so it can't detect the the invoice was created before .
if we change the template with an other pdf name  it print it also

**Comment by Garamotte** [comment]
Someone else reported me the issue, while testing the v10 migration.

Looking at te code, I think the fix would be to inherit the `generate_email` method of `mail.template` to add `must_skip_send_to_printer` in the context.

**Comment by Garamotte** [comment]
Fixed by https://github.com/OCA/report-print-send/pull/78
@PhilippeBach You'll just have to install the new `base_report_to_printer_mail` module, if it doesn't install automatically.
