### ISSUE TITLE
error printing invoice from POS

### ISSUE THREAD

**Issue by efarias** [OCA/report-print-send#63]
Trying to print an invoice from POS, odoo 9.0, it gives me this error:

> 2016-11-02 21:09:32,939 15700 ERROR BaltoluProductionStable2016 openerp.http: Exception during JSON request handling.
> Traceback (most recent call last):
>   File "/opt/odoo/openerp/http.py", line 643, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/opt/odoo/openerp/http.py", line 680, in dispatch
>     result = self._call_function(**self.params)
>   File "/opt/odoo/openerp/http.py", line 316, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/opt/odoo/openerp/http.py", line 309, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/opt/odoo/openerp/http.py", line 959, in __call__
>     return self.method(*args, **kw)
>   File "/opt/odoo/openerp/http.py", line 509, in response_wrap
>     response = f(*args, **kw)
>   File "/opt/odoo/addons/web/controllers/main.py", line 892, in call_kw
>     return self._call_kw(model, method, args, kwargs)
>   File "/opt/odoo/addons/web/controllers/main.py", line 884, in _call_kw
>     return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
>   File "/opt/odoo/openerp/api.py", line 238, in wrapper
>     return old_api(self, *args, **kwargs)
>   File "/opt/odoo/openerp/api.py", line 369, in old_api
>     result = method(recs, *args, **kwargs)
>   File "/opt/odoo/addons/base_report_to_printer/models/report.py", line 21, in print_document
>     document = rec_id.get_pdf(report_name, html=html, data=data)
>   File "/opt/odoo/openerp/api.py", line 236, in wrapper
>     return new_api(self, *args, **kwargs)
> TypeError: get_pdf() takes at least 3 arguments (4 given)

**Comment by auphofBSF** [comment]
Same Issue as **efarias**, I have looked into it and found a fix,  as per image,   rec_id requires to be passed to the get_pdf call as 1st parameter
![image](https://cloud.githubusercontent.com/assets/11743864/20461585/795b8830-af67-11e6-9c1b-c913613637a5.png)

**Comment by auphofBSF** [comment]
Pull Request created: [FIX] 9.0 Issue#63 printing now working #67

**Comment by lasley** [comment]
This was fixed & merged in #77
