### ISSUE TITLE
server print error and fails to link CUPS when printing 

### ISSUE THREAD

**Issue by nonofpy** [OCA/report-print-send#75]
Hi All, 

I am working in Odoo 9.0 and installed the module 'report to printer'. But I got the following issues.
CUPS connects to the Odoo successfully. Because I can get the server and printers information in CUPS as well as the real-time jobs. 

1. server error when I print  as 'pdf' type
- configure the reports settings
![image](https://cloud.githubusercontent.com/assets/20656150/22767131/7c7f866a-eeb4-11e6-8142-d4e3bb1ad660.png)
- print the SO, and get the below error 
![image](https://cloud.githubusercontent.com/assets/20656150/22767155/96f3238a-eeb4-11e6-81fd-afb96f568f34.png)

2. still link to the local printer instead of CUPS
- configure the reports -> as 'html' (without server errors)
- result -> popup a local printing page

Do I miss something in the configuration ? It seems that Odoo can not link to CUPS.

Please help!

Thank you so much. 

Regards,
Betty

**Comment by Garamotte** [comment]
Fixed by https://github.com/OCA/report-print-send/pull/77
