### ISSUE TITLE
[8.0] Not printing barcode

### ISSUE THREAD

**Issue by aitorbouzas** [OCA/report-print-send#80]
Hello everyone,

I have an automated action that prints sales orders automatically. The problem is that if I click to print the report it prints correctly through the printer, but when the automation goes through the sales order there's a barcode (that prints correctly when printing it manual) that just stays blank.

This is the code that launches the print:
```
for sale in  sale_obj.browse(cr, uid, sale_ids, context=context):
    context.update({'lang': 'es_ES',
        'search_default_my_sale_orders_filter': 1,
        'tz': 'Europe/Madrid',
        'uid': 1,
        'active_model': 'sale.order',
        'search_disable_custom_filters': True,
        'active_ids': [sale.id],
        'active_id': sale.id})
    print_sale = self.pool['report'].print_document(cr, uid, [sale.id],'acp_rc_proforma.report_saleorder_direct_print',html=None,data={}, context=context)
```

And this is the lines of the report that shows up the barcode:
`<img t-att-src="'/report/barcode/?type=%s&amp;value=%s&amp;width=%s&amp;height=%s' % ('Code128', o.name, 600, 100)" style="width:300px;height:50px" />`

The thing is... this worked correctly some time ago, but then I did an update of the odoo server and just stopped working... Any help would be very appreciated.

**Comment by aitorbouzas** [comment]
Can someone help me with this?

**Comment by pedrobaeza** [comment]
This is not an issue with any module in this project, so please ask this on the forums/mailing list.
