### ISSUE TITLE
Prints when e-mails are sent

### ISSUE THREAD

**Issue by gregimagines** [OCA/report-print-send#98]
We have the module installed on Ubuntu 16.04 with Odoo Enterprise 10. After some configuring of our printers, we were able to get things running. However, whenever we open a sales order and click send by email, it automatically prints based on our printer settings. Every time we send an email it prints a copy of the attachment. We are getting hundreds of printouts that should not be printing. Cannot find a way to turn this off.

**Comment by Garamotte** [comment]
See this module: https://github.com/OCA/report-print-send/tree/9.0/base_report_to_printer_mail
It should be easy to migrate to v10.

**Comment by gregimagines** [comment]
Looks like that solves the issue. A few items have popped up but not sure if they're related or not. Thanks.
